//! The book's generated fragments: every number a chapter prints, computed by the reader.
//!
//! A chapter never types a byte count, an offset or a request total. It `{include}`s a fragment
//! from `chapters/_generated/`, and this module writes those fragments by running the reader over
//! the committed fixtures. `pqlab figures --check` fails when a committed fragment differs from
//! what the reader now computes, so a change to the reader or a fixture cannot leave a chapter
//! printing an old number.
//!
//! Each fragment ends with the conditions it was computed under: which fixture, and which
//! simulated network. A figure without its conditions is a number without a source.

use std::path::Path;
use std::process::ExitCode;

use parquet_lab::format::{footer_span, parse_trailer};
use parquet_lab::json::Json;
use parquet_lab::metadata::FileMetaData;
use parquet_lab::object_store::{MemoryStore, NetworkModel, TracingStore};
use parquet_lab::reader::{read_footer, FooterOptions, SizeSource};
use parquet_lab::report::{layouts, open_bytes};

struct Figure {
    file: &'static str,
    render: fn(&Path) -> Result<String, String>,
}

const FIGURES: &[Figure] = &[
    Figure {
        file: "layouts-costs.md",
        render: layouts_costs,
    },
    Figure {
        file: "tiny-regions.md",
        render: tiny_regions,
    },
    Figure {
        file: "tiny-trailer.md",
        render: tiny_trailer,
    },
    Figure {
        file: "tiny-trace.md",
        render: tiny_trace,
    },
    Figure {
        file: "footer-strategies.md",
        render: footer_strategies,
    },
];

pub fn run(root: &Path, out: &Path, check: bool) -> Result<ExitCode, String> {
    let dir = root.join(out);
    if !check {
        std::fs::create_dir_all(&dir)
            .map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
    }
    let mut stale = Vec::new();
    for fig in FIGURES {
        let body = (fig.render)(root)?;
        let path = dir.join(fig.file);
        if check {
            if std::fs::read_to_string(&path).ok().as_deref() != Some(body.as_str()) {
                stale.push(path.display().to_string());
            }
        } else {
            std::fs::write(&path, &body)
                .map_err(|e| format!("cannot write {}: {e}", path.display()))?;
            println!("wrote {}", path.display());
        }
    }
    if !stale.is_empty() {
        eprintln!("stale fragments (run `make figures` and commit):");
        for s in stale {
            eprintln!("  {s}");
        }
        return Ok(ExitCode::from(1));
    }
    if check {
        println!(
            "  {} fragments match what the reader computes",
            FIGURES.len()
        );
    }
    Ok(ExitCode::SUCCESS)
}

const HEADER: &str =
    "% Generated by `pqlab figures` (crates/pqlab/src/figures.rs). Do not edit.\n\n";

fn fixture(root: &Path, name: &str) -> Result<Vec<u8>, String> {
    let path = root.join("fixtures").join(name);
    std::fs::read(&path).map_err(|e| format!("cannot read {}: {e}", path.display()))
}

fn conditions(name: &str, bytes: &[u8], model: Option<NetworkModel>) -> String {
    let mut s = format!(
        "\n*Computed by the reader from `fixtures/{name}` ({} bytes).",
        bytes.len()
    );
    if let Some(m) = model {
        s.push_str(&format!(
            " Simulated network: {} per request, {} once data flows.",
            ms(m.latency_us),
            rate(m.bandwidth_bytes_per_sec)
        ));
    }
    s.push_str("*\n");
    s
}

fn ms(us: u64) -> String {
    let v = us as f64 / 1000.0;
    if us % 1000 == 0 {
        format!("{v:.0} ms")
    } else {
        format!("{v:.3} ms")
    }
}

fn rate(bps: u64) -> String {
    match bps {
        0 => "unlimited bandwidth".into(),
        b if b % 1_000_000 == 0 => format!("{} MB/s", b / 1_000_000),
        b => format!("{b} bytes/s"),
    }
}

/// `16777216` as `16,777,216`.
fn thousands(n: u64) -> String {
    let digits = n.to_string();
    let mut out = String::new();
    for (i, c) in digits.chars().enumerate() {
        if i > 0 && (digits.len() - i) % 3 == 0 {
            out.push(',');
        }
        out.push(c);
    }
    out
}

fn metadata(bytes: &[u8]) -> Result<FileMetaData, String> {
    open_bytes(bytes)
}

fn tiny_regions(root: &Path) -> Result<String, String> {
    let name = "tiny.parquet";
    let bytes = fixture(root, name)?;
    let size = bytes.len() as u64;
    let last8: [u8; 8] = bytes[bytes.len() - 8..].try_into().unwrap();
    let trailer = parse_trailer(last8, size).map_err(|e| e.to_string())?;
    let footer = footer_span(size, trailer.footer_length).map_err(|e| e.to_string())?;
    let md = metadata(&bytes)?;
    let mut rows = vec![("Opening magic `PAR1`".to_string(), 0, 4)];
    for (i, rg) in md.row_groups.iter().enumerate() {
        let spans: Vec<_> = rg.columns.iter().map(|c| c.byte_range()).collect();
        let start = spans.iter().map(|s| s.start).min().unwrap_or(4);
        let end = spans.iter().map(|s| s.end).max().unwrap_or(4);
        rows.push((format!("Row group {i}"), start, end));
        for c in &rg.columns {
            let s = c.byte_range();
            rows.push((
                format!("  Column chunk `{}`", c.dotted_path()),
                s.start,
                s.end,
            ));
        }
    }
    rows.push(("Footer (`FileMetaData`)".into(), footer.start, footer.end));
    rows.push((
        "Footer length".into(),
        trailer.length_span().start,
        trailer.length_span().end,
    ));
    rows.push((
        "Closing magic `PAR1`".into(),
        trailer.magic_span().start,
        trailer.magic_span().end,
    ));
    let mut s = String::from(HEADER);
    s.push_str("| Region | Starts at | Ends before | Length |\n|---|--:|--:|--:|\n");
    for (label, a, b) in rows {
        let label = match label.strip_prefix("  ") {
            Some(inner) => format!("↳ {inner}"),
            None => label,
        };
        s.push_str(&format!("| {label} | {a} | {b} | {} |\n", b - a));
    }
    s.push_str(&conditions(name, &bytes, None));
    Ok(s)
}

fn tiny_trailer(root: &Path) -> Result<String, String> {
    let name = "tiny.parquet";
    let bytes = fixture(root, name)?;
    let size = bytes.len() as u64;
    let last8: [u8; 8] = bytes[bytes.len() - 8..].try_into().unwrap();
    let t = parse_trailer(last8, size).map_err(|e| e.to_string())?;
    let footer = footer_span(size, t.footer_length).map_err(|e| e.to_string())?;
    let mut s = String::from(HEADER);
    s.push_str("| Offset | Byte | ASCII | Part |\n|--:|---|---|---|\n");
    for (i, b) in t.bytes.iter().enumerate() {
        let part = if i < 4 {
            "footer length"
        } else {
            "closing magic"
        };
        // A pipe would end the table cell, even inside backticks, unless it is escaped.
        let ascii = match *b {
            b'|' => "`\\|`".to_string(),
            b if b.is_ascii_graphic() => format!("`{}`", b as char),
            _ => "·".into(),
        };
        s.push_str(&format!(
            "| {} | `{b:02x}` | {ascii} | {part} |\n",
            t.span.start + i as u64
        ));
    }
    let terms: Vec<String> = t
        .length_terms()
        .iter()
        .map(|(b, w)| format!("`{b:02x}` × {}", thousands(*w)))
        .collect();
    s.push_str(&format!(
        "\nRead as a little-endian `u32`: {} = **{}**.\n\n",
        terms.join(" + "),
        t.footer_length
    ));
    s.push_str(&format!(
        "So the footer starts at {size} − 8 − {} = **{}** and ends before {size} − 8 = **{}**.\n",
        t.footer_length, footer.start, footer.end
    ));
    s.push_str(&conditions(name, &bytes, None));
    Ok(s)
}

fn trace_for(
    bytes: &[u8],
    key: &str,
    options: FooterOptions,
    model: NetworkModel,
) -> Result<TracingStore<MemoryStore>, String> {
    let mut store = MemoryStore::new();
    store.put(key, bytes.to_vec());
    let mut traced = TracingStore::new(store, model);
    read_footer(&mut traced, key, options).map_err(|e| e.to_string())?;
    Ok(traced)
}

fn tiny_trace(root: &Path) -> Result<String, String> {
    let name = "tiny.parquet";
    let bytes = fixture(root, name)?;
    let model = NetworkModel::default();
    let traced = trace_for(&bytes, name, FooterOptions::default(), model)?;
    let mut s = String::from(HEADER);
    s.push_str(
        "| # | Request | `Range` | Bytes back | Finished at | Why |\n|--:|---|---|--:|--:|---|\n",
    );
    for r in &traced.requests {
        s.push_str(&format!(
            "| {} | `{} /{}` | {} | {} | {} | {} |\n",
            r.seq,
            r.method.name(),
            r.key,
            r.range
                .as_deref()
                .map(|h| format!("`{h}`"))
                .unwrap_or("·".into()),
            r.bytes_returned,
            ms(r.end_us),
            r.why
        ));
    }
    s.push_str(&format!(
        "\n{} requests, {} bytes transferred, {} of simulated time before the first value could be read.\n",
        traced.requests.len(),
        traced.bytes_returned(),
        ms(traced.elapsed_us())
    ));
    s.push_str(&conditions(name, &bytes, Some(model)));
    Ok(s)
}

fn footer_strategies(root: &Path) -> Result<String, String> {
    let model = NetworkModel::default();
    let prefetch = 64 * 1024;
    let mut s = String::from(HEADER);
    s.push_str(
        "| File | How the size is found | Tail read | Requests | Bytes back | Simulated time |\n\
         |---|---|--:|--:|--:|--:|\n",
    );
    let mut sizes = Vec::new();
    for name in ["tiny.parquet", "multiple-row-groups.parquet"] {
        let bytes = fixture(root, name)?;
        sizes.push(format!("`{name}` is {} bytes", bytes.len()));
        let size = bytes.len() as u64;
        let strategies: [(&str, FooterOptions); 4] = [
            (
                "`HEAD`",
                FooterOptions {
                    size: SizeSource::Head,
                    prefetch: 8,
                },
            ),
            (
                "from a listing",
                FooterOptions {
                    size: SizeSource::Known(size),
                    prefetch: 8,
                },
            ),
            (
                "suffix range",
                FooterOptions {
                    size: SizeSource::SuffixRange,
                    prefetch: 8,
                },
            ),
            (
                "suffix range",
                FooterOptions {
                    size: SizeSource::SuffixRange,
                    prefetch,
                },
            ),
        ];
        for (how, options) in strategies {
            let traced = trace_for(&bytes, name, options, model)?;
            s.push_str(&format!(
                "| `{name}` | {how} | {} | {} | {} | {} |\n",
                options.prefetch,
                traced.requests.len(),
                traced.bytes_returned(),
                ms(traced.elapsed_us())
            ));
        }
    }
    s.push_str(&format!(
        "\n*Computed by the reader from the fixtures: {}. Simulated network: {} per request, {} once data flows.*\n",
        sizes.join(", "),
        ms(model.latency_us),
        rate(model.bandwidth_bytes_per_sec)
    ));
    Ok(s)
}

fn layouts_costs(_root: &Path) -> Result<String, String> {
    let model = NetworkModel::default();
    let all = |r: &Json, k: &str| -> Result<(u64, u64, u64, u64, u64, u64), String> {
        let l = r.get(k).ok_or("no layout")?;
        let n = |j: Option<&Json>| j.and_then(Json::as_u64).ok_or("missing number".to_string());
        Ok((
            n(l.get("needed_bytes"))?,
            l.get("needed")
                .and_then(Json::as_array)
                .map(|a| a.len() as u64)
                .unwrap_or(0),
            n(l.get("by_range").and_then(|b| b.get("elapsed_us")))?,
            n(l.get("whole").and_then(|b| b.get("bytes")))?,
            n(l.get("whole").and_then(|b| b.get("elapsed_us")))?,
            n(l.get("total_bytes"))?,
        ))
    };
    // Bits are column positions: order_id, customer_id, country, amount_cents, order_date.
    let queries: [(&str, u32, Option<usize>); 3] = [
        ("`SELECT country, amount_cents FROM sales`", 0b01100, None),
        ("`SELECT amount_cents FROM sales`", 0b01000, None),
        ("`SELECT * FROM sales WHERE order_id = 4`", 0b11111, Some(3)),
    ];
    let mut s = String::from(HEADER);
    s.push_str(
        "| Query | Layout | Bytes needed | Separate ranges | Fetch each range | Fetch the whole object |\n\
         |---|---|--:|--:|--:|--:|\n",
    );
    let mut total = 0;
    for (sql, mask, row) in queries {
        let r = layouts(mask, row, model);
        for (key, name) in [("rows_layout", "rows"), ("columns_layout", "columns")] {
            let (need, ranges, each_us, whole_bytes, whole_us, t) = all(&r, key)?;
            total = t;
            s.push_str(&format!(
                "| {sql} | {name} | {need} | {ranges} | {ranges} request{}, {} | {whole_bytes} bytes, {} |\n",
                if ranges == 1 { "" } else { "s" },
                ms(each_us),
                ms(whole_us)
            ));
        }
    }
    s.push_str(&format!(
        "\n*Computed by the reader from the eight-order sales table in `crates/parquet-lab/src/layout.rs`, \
         {total} bytes in either layout. Simulated network: {} per request, {} once data flows.*\n",
        ms(model.latency_us),
        rate(model.bandwidth_bytes_per_sec)
    ));
    Ok(s)
}
