//! The book's generated fragments: every number a chapter prints, computed by the reader.
//!
//! A chapter never types a byte count, an offset or a request total. It `{include}`s a fragment
//! from `chapters/_generated/`, and this module writes those fragments by running the reader over
//! the committed fixtures. `pqlab figures --check` fails when a committed fragment differs from
//! what the reader now computes, so a change to the reader or a fixture cannot leave a chapter
//! printing an old number.
//!
//! Each fragment ends with the conditions it was computed under: which fixture, and which
//! simulated network. A figure without its conditions is a number without a source.

use std::path::Path;
use std::process::ExitCode;

use parquet_lab::format::{footer_span, parse_trailer};
use parquet_lab::json::Json;
use parquet_lab::metadata::FileMetaData;
use parquet_lab::object_store::{MemoryStore, NetworkModel, TracingStore};
use parquet_lab::reader::{read_footer, FooterOptions, SizeSource};
use parquet_lab::report::{layouts, open_bytes};

struct Figure {
    file: &'static str,
    render: fn(&Path) -> Result<String, String>,
}

const FIGURES: &[Figure] = &[
    Figure {
        file: "layouts-costs.md",
        render: layouts_costs,
    },
    Figure {
        file: "tiny-regions.md",
        render: tiny_regions,
    },
    Figure {
        file: "tiny-trailer.md",
        render: tiny_trailer,
    },
    Figure {
        file: "tiny-trace.md",
        render: tiny_trace,
    },
    Figure {
        file: "footer-strategies.md",
        render: footer_strategies,
    },
    Figure {
        file: "types-schema-flat.md",
        render: types_schema_flat,
    },
    Figure {
        file: "types-schema-text.md",
        render: types_schema_text,
    },
    Figure {
        file: "types-values.md",
        render: types_values,
    },
    Figure {
        file: "nested-schema-text.md",
        render: nested_schema_text,
    },
    Figure {
        file: "nested-columns.md",
        render: nested_columns,
    },
    Figure {
        file: "nested-levels-email.md",
        render: |root| nested_levels(root, "email"),
    },
    Figure {
        file: "nested-levels-tags.md",
        render: |root| nested_levels(root, "tags.list.element"),
    },
    Figure {
        file: "nested-levels-discounts.md",
        render: |root| nested_levels(root, "items.list.element.discounts.list.element"),
    },
    Figure {
        file: "nested-runs-discounts.md",
        render: nested_runs_discounts,
    },
    Figure {
        file: "encodings-sizes.md",
        render: encodings_sizes,
    },
    Figure {
        file: "dictionary-country.md",
        render: dictionary_country,
    },
    Figure {
        file: "delta-ordered-at.md",
        render: delta_ordered_at,
    },
    Figure {
        file: "delta-urls.md",
        render: delta_urls,
    },
    Figure {
        file: "split-weights.md",
        render: split_weights,
    },
];

pub fn run(root: &Path, out: &Path, check: bool) -> Result<ExitCode, String> {
    let dir = root.join(out);
    if !check {
        std::fs::create_dir_all(&dir)
            .map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
    }
    let mut stale = Vec::new();
    for fig in FIGURES {
        let body = (fig.render)(root)?;
        let path = dir.join(fig.file);
        if check {
            if std::fs::read_to_string(&path).ok().as_deref() != Some(body.as_str()) {
                stale.push(path.display().to_string());
            }
        } else {
            std::fs::write(&path, &body)
                .map_err(|e| format!("cannot write {}: {e}", path.display()))?;
            println!("wrote {}", path.display());
        }
    }
    if !stale.is_empty() {
        eprintln!("stale fragments (run `make figures` and commit):");
        for s in stale {
            eprintln!("  {s}");
        }
        return Ok(ExitCode::from(1));
    }
    if check {
        println!(
            "  {} fragments match what the reader computes",
            FIGURES.len()
        );
    }
    Ok(ExitCode::SUCCESS)
}

const HEADER: &str =
    "% Generated by `pqlab figures` (crates/pqlab/src/figures.rs). Do not edit.\n\n";

fn fixture(root: &Path, name: &str) -> Result<Vec<u8>, String> {
    let path = root.join("fixtures").join(name);
    std::fs::read(&path).map_err(|e| format!("cannot read {}: {e}", path.display()))
}

fn conditions(name: &str, bytes: &[u8], model: Option<NetworkModel>) -> String {
    let mut s = format!(
        "\n*Computed by the reader from `fixtures/{name}` ({} bytes).",
        bytes.len()
    );
    if let Some(m) = model {
        s.push_str(&format!(
            " Simulated network: {} per request, {} once data flows.",
            ms(m.latency_us),
            rate(m.bandwidth_bytes_per_sec)
        ));
    }
    s.push_str("*\n");
    s
}

fn ms(us: u64) -> String {
    let v = us as f64 / 1000.0;
    if us % 1000 == 0 {
        format!("{v:.0} ms")
    } else {
        format!("{v:.3} ms")
    }
}

fn rate(bps: u64) -> String {
    match bps {
        0 => "unlimited bandwidth".into(),
        b if b % 1_000_000 == 0 => format!("{} MB/s", b / 1_000_000),
        b => format!("{b} bytes/s"),
    }
}

/// `16777216` as `16,777,216`.
fn thousands(n: u64) -> String {
    let digits = n.to_string();
    let mut out = String::new();
    for (i, c) in digits.chars().enumerate() {
        if i > 0 && (digits.len() - i) % 3 == 0 {
            out.push(',');
        }
        out.push(c);
    }
    out
}

fn metadata(bytes: &[u8]) -> Result<FileMetaData, String> {
    open_bytes(bytes)
}

fn tiny_regions(root: &Path) -> Result<String, String> {
    let name = "tiny.parquet";
    let bytes = fixture(root, name)?;
    let size = bytes.len() as u64;
    let last8: [u8; 8] = bytes[bytes.len() - 8..].try_into().unwrap();
    let trailer = parse_trailer(last8, size).map_err(|e| e.to_string())?;
    let footer = footer_span(size, trailer.footer_length).map_err(|e| e.to_string())?;
    let md = metadata(&bytes)?;
    let mut rows = vec![("Opening magic `PAR1`".to_string(), 0, 4)];
    for (i, rg) in md.row_groups.iter().enumerate() {
        let spans: Vec<_> = rg.columns.iter().map(|c| c.byte_range()).collect();
        let start = spans.iter().map(|s| s.start).min().unwrap_or(4);
        let end = spans.iter().map(|s| s.end).max().unwrap_or(4);
        rows.push((format!("Row group {i}"), start, end));
        for c in &rg.columns {
            let s = c.byte_range();
            rows.push((
                format!("  Column chunk `{}`", c.dotted_path()),
                s.start,
                s.end,
            ));
        }
    }
    rows.push(("Footer (`FileMetaData`)".into(), footer.start, footer.end));
    rows.push((
        "Footer length".into(),
        trailer.length_span().start,
        trailer.length_span().end,
    ));
    rows.push((
        "Closing magic `PAR1`".into(),
        trailer.magic_span().start,
        trailer.magic_span().end,
    ));
    let mut s = String::from(HEADER);
    s.push_str("| Region | Starts at | Ends before | Length |\n|---|--:|--:|--:|\n");
    for (label, a, b) in rows {
        let label = match label.strip_prefix("  ") {
            Some(inner) => format!("↳ {inner}"),
            None => label,
        };
        s.push_str(&format!("| {label} | {a} | {b} | {} |\n", b - a));
    }
    s.push_str(&conditions(name, &bytes, None));
    Ok(s)
}

fn tiny_trailer(root: &Path) -> Result<String, String> {
    let name = "tiny.parquet";
    let bytes = fixture(root, name)?;
    let size = bytes.len() as u64;
    let last8: [u8; 8] = bytes[bytes.len() - 8..].try_into().unwrap();
    let t = parse_trailer(last8, size).map_err(|e| e.to_string())?;
    let footer = footer_span(size, t.footer_length).map_err(|e| e.to_string())?;
    let mut s = String::from(HEADER);
    s.push_str("| Offset | Byte | ASCII | Part |\n|--:|---|---|---|\n");
    for (i, b) in t.bytes.iter().enumerate() {
        let part = if i < 4 {
            "footer length"
        } else {
            "closing magic"
        };
        // A pipe would end the table cell, even inside backticks, unless it is escaped.
        let ascii = match *b {
            b'|' => "`\\|`".to_string(),
            b if b.is_ascii_graphic() => format!("`{}`", b as char),
            _ => "·".into(),
        };
        s.push_str(&format!(
            "| {} | `{b:02x}` | {ascii} | {part} |\n",
            t.span.start + i as u64
        ));
    }
    let terms: Vec<String> = t
        .length_terms()
        .iter()
        .map(|(b, w)| format!("`{b:02x}` × {}", thousands(*w)))
        .collect();
    s.push_str(&format!(
        "\nRead as a little-endian `u32`: {} = **{}**.\n\n",
        terms.join(" + "),
        t.footer_length
    ));
    s.push_str(&format!(
        "So the footer starts at {size} − 8 − {} = **{}** and ends before {size} − 8 = **{}**.\n",
        t.footer_length, footer.start, footer.end
    ));
    s.push_str(&conditions(name, &bytes, None));
    Ok(s)
}

fn trace_for(
    bytes: &[u8],
    key: &str,
    options: FooterOptions,
    model: NetworkModel,
) -> Result<TracingStore<MemoryStore>, String> {
    let mut store = MemoryStore::new();
    store.put(key, bytes.to_vec());
    let mut traced = TracingStore::new(store, model);
    read_footer(&mut traced, key, options).map_err(|e| e.to_string())?;
    Ok(traced)
}

fn tiny_trace(root: &Path) -> Result<String, String> {
    let name = "tiny.parquet";
    let bytes = fixture(root, name)?;
    let model = NetworkModel::default();
    let traced = trace_for(&bytes, name, FooterOptions::default(), model)?;
    let mut s = String::from(HEADER);
    s.push_str(
        "| # | Request | `Range` | Bytes back | Finished at | Why |\n|--:|---|---|--:|--:|---|\n",
    );
    for r in &traced.requests {
        s.push_str(&format!(
            "| {} | `{} /{}` | {} | {} | {} | {} |\n",
            r.seq,
            r.method.name(),
            r.key,
            r.range
                .as_deref()
                .map(|h| format!("`{h}`"))
                .unwrap_or("·".into()),
            r.bytes_returned,
            ms(r.end_us),
            r.why
        ));
    }
    s.push_str(&format!(
        "\n{} requests, {} bytes transferred, {} of simulated time before the first value could be read.\n",
        traced.requests.len(),
        traced.bytes_returned(),
        ms(traced.elapsed_us())
    ));
    s.push_str(&conditions(name, &bytes, Some(model)));
    Ok(s)
}

fn footer_strategies(root: &Path) -> Result<String, String> {
    let model = NetworkModel::default();
    let prefetch = 64 * 1024;
    let mut s = String::from(HEADER);
    s.push_str(
        "| File | How the size is found | Tail read | Requests | Bytes back | Simulated time |\n\
         |---|---|--:|--:|--:|--:|\n",
    );
    let mut sizes = Vec::new();
    for name in ["tiny.parquet", "multiple-row-groups.parquet"] {
        let bytes = fixture(root, name)?;
        sizes.push(format!("`{name}` is {} bytes", bytes.len()));
        let size = bytes.len() as u64;
        let strategies: [(&str, FooterOptions); 4] = [
            (
                "`HEAD`",
                FooterOptions {
                    size: SizeSource::Head,
                    prefetch: 8,
                },
            ),
            (
                "from a listing",
                FooterOptions {
                    size: SizeSource::Known(size),
                    prefetch: 8,
                },
            ),
            (
                "suffix range",
                FooterOptions {
                    size: SizeSource::SuffixRange,
                    prefetch: 8,
                },
            ),
            (
                "suffix range",
                FooterOptions {
                    size: SizeSource::SuffixRange,
                    prefetch,
                },
            ),
        ];
        for (how, options) in strategies {
            let traced = trace_for(&bytes, name, options, model)?;
            s.push_str(&format!(
                "| `{name}` | {how} | {} | {} | {} | {} |\n",
                options.prefetch,
                traced.requests.len(),
                traced.bytes_returned(),
                ms(traced.elapsed_us())
            ));
        }
    }
    s.push_str(&format!(
        "\n*Computed by the reader from the fixtures: {}. Simulated network: {} per request, {} once data flows.*\n",
        sizes.join(", "),
        ms(model.latency_us),
        rate(model.bandwidth_bytes_per_sec)
    ));
    Ok(s)
}

fn layouts_costs(_root: &Path) -> Result<String, String> {
    let model = NetworkModel::default();
    let all = |r: &Json, k: &str| -> Result<(u64, u64, u64, u64, u64, u64), String> {
        let l = r.get(k).ok_or("no layout")?;
        let n = |j: Option<&Json>| j.and_then(Json::as_u64).ok_or("missing number".to_string());
        Ok((
            n(l.get("needed_bytes"))?,
            l.get("needed")
                .and_then(Json::as_array)
                .map(|a| a.len() as u64)
                .unwrap_or(0),
            n(l.get("by_range").and_then(|b| b.get("elapsed_us")))?,
            n(l.get("whole").and_then(|b| b.get("bytes")))?,
            n(l.get("whole").and_then(|b| b.get("elapsed_us")))?,
            n(l.get("total_bytes"))?,
        ))
    };
    // Bits are column positions: order_id, customer_id, country, amount_cents, order_date.
    let queries: [(&str, u32, Option<usize>); 3] = [
        ("`SELECT country, amount_cents FROM sales`", 0b01100, None),
        ("`SELECT amount_cents FROM sales`", 0b01000, None),
        ("`SELECT * FROM sales WHERE order_id = 4`", 0b11111, Some(3)),
    ];
    let mut s = String::from(HEADER);
    s.push_str(
        "| Query | Layout | Bytes needed | Separate ranges | Fetch each range | Fetch the whole object |\n\
         |---|---|--:|--:|--:|--:|\n",
    );
    let mut total = 0;
    for (sql, mask, row) in queries {
        let r = layouts(mask, row, model);
        for (key, name) in [("rows_layout", "rows"), ("columns_layout", "columns")] {
            let (need, ranges, each_us, whole_bytes, whole_us, t) = all(&r, key)?;
            total = t;
            s.push_str(&format!(
                "| {sql} | {name} | {need} | {ranges} | {ranges} request{}, {} | {whole_bytes} bytes, {} |\n",
                if ranges == 1 { "" } else { "s" },
                ms(each_us),
                ms(whole_us)
            ));
        }
    }
    s.push_str(&format!(
        "\n*Computed by the reader from the eight-order sales table in `crates/parquet-lab/src/layout.rs`, \
         {total} bytes in either layout. Simulated network: {} per request, {} once data flows.*\n",
        ms(model.latency_us),
        rate(model.bandwidth_bytes_per_sec)
    ));
    Ok(s)
}

fn types_schema(root: &Path) -> Result<(Vec<u8>, Json), String> {
    let bytes = fixture(root, "types.parquet")?;
    let j = parquet_lab::report::schema(&bytes);
    if j.get("ok") != Some(&Json::Bool(true)) {
        return Err(format!("types.parquet: {}", j.to_json()));
    }
    Ok((bytes, j))
}

fn text_of(j: Option<&Json>) -> String {
    match j {
        Some(Json::Str(s)) => s.clone(),
        Some(Json::Null) | None => String::new(),
        Some(other) => other.to_json(),
    }
}

fn types_schema_flat(root: &Path) -> Result<String, String> {
    let (bytes, j) = types_schema(root)?;
    let mut s = String::from(HEADER);
    s.push_str("| # | Name | Children | Repetition | Physical type | Logical type |\n|--:|---|--:|---|---|---|\n");
    for e in j
        .get("elements")
        .and_then(Json::as_array)
        .ok_or("no elements")?
    {
        let physical = text_of(e.get("physical_type"));
        let physical = match e.get("type_length").and_then(Json::as_i64) {
            Some(n) if !physical.is_empty() => format!("{physical}({n})"),
            _ => physical,
        };
        s.push_str(&format!(
            "| {} | `{}` | {} | {} | {} | {} |\n",
            text_of(e.get("index")),
            text_of(e.get("name")),
            text_of(e.get("num_children")),
            text_of(e.get("repetition")).to_lowercase(),
            if physical.is_empty() {
                "(group)".into()
            } else {
                physical
            },
            text_of(e.get("logical_type")),
        ));
    }
    s.push_str(&conditions("types.parquet", &bytes, None));
    Ok(s)
}

fn types_schema_text(root: &Path) -> Result<String, String> {
    let (bytes, j) = types_schema(root)?;
    let mut s = String::from(HEADER);
    s.push_str("```text\n");
    s.push_str(&text_of(j.get("text")));
    s.push_str("```\n");
    s.push_str(&conditions("types.parquet", &bytes, None));
    Ok(s)
}

fn types_values(root: &Path) -> Result<String, String> {
    let (bytes, j) = types_schema(root)?;
    let mut s = String::from(HEADER);
    s.push_str(
        "| Column | Physical type | Logical type | Minimum, as stored | Read as the physical type | Read through the logical type |\n\
         |---|---|---|---|---|---|\n",
    );
    for l in j
        .get("leaves")
        .and_then(Json::as_array)
        .ok_or("no leaves")?
    {
        let min = l.get("statistics").and_then(|st| st.get("min"));
        let cell = |k: &str| {
            let v = text_of(min.and_then(|m| m.get(k)));
            if v.is_empty() {
                "·".to_string()
            } else {
                format!("`{}`", v.replace('`', ""))
            }
        };
        s.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} |\n",
            text_of(l.get("path")),
            text_of(l.get("physical_type")),
            match text_of(l.get("logical_type")) {
                t if t.is_empty() => "·".to_string(),
                t => t,
            },
            cell("hex"),
            cell("physical"),
            cell("logical"),
        ));
    }
    s.push_str(&conditions("types.parquet", &bytes, None));
    Ok(s)
}

fn nested_levels_json(root: &Path, path: &str) -> Result<(Vec<u8>, Json), String> {
    let bytes = fixture(root, "nested.parquet")?;
    let all = parquet_lab::report::levels(&bytes, 0);
    let column = all
        .get("columns")
        .and_then(Json::as_array)
        .and_then(|cs| cs.iter().find(|c| text_of(c.get("path")) == path))
        .and_then(|c| c.get("column"))
        .and_then(Json::as_u64)
        .ok_or(format!("nested.parquet has no column {path}"))?;
    let j = parquet_lab::report::levels(&bytes, column as usize);
    if j.get("ok") != Some(&Json::Bool(true)) {
        return Err(format!("nested.parquet {path}: {}", j.to_json()));
    }
    Ok((bytes, j))
}

fn nested_schema_text(root: &Path) -> Result<String, String> {
    let bytes = fixture(root, "nested.parquet")?;
    let j = parquet_lab::report::schema(&bytes);
    let mut s = String::from(HEADER);
    s.push_str("```text\n");
    s.push_str(&text_of(j.get("text")));
    s.push_str("```\n");
    s.push_str(&conditions("nested.parquet", &bytes, None));
    Ok(s)
}

fn nested_columns(root: &Path) -> Result<String, String> {
    let bytes = fixture(root, "nested.parquet")?;
    let j = parquet_lab::report::levels(&bytes, 0);
    let mut s = String::from(HEADER);
    s.push_str("| Column | Path in the file | Max definition level | Max repetition level |\n|---|---|--:|--:|\n");
    for c in j
        .get("columns")
        .and_then(Json::as_array)
        .ok_or("no columns")?
    {
        s.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            text_of(c.get("label")),
            text_of(c.get("path")),
            text_of(c.get("max_definition_level")),
            text_of(c.get("max_repetition_level")),
        ));
    }
    s.push_str(&conditions("nested.parquet", &bytes, None));
    Ok(s)
}

fn nested_levels(root: &Path, path: &str) -> Result<String, String> {
    let (bytes, j) = nested_levels_json(root, path)?;
    let mut s = String::from(HEADER);
    s.push_str("| r | d | Value | What the levels say |\n|--:|--:|---|---|\n");
    for t in j
        .get("triples")
        .and_then(Json::as_array)
        .ok_or("no triples")?
    {
        let value = match t.get("value") {
            Some(Json::Null) | None => "·".to_string(),
            Some(v) => format!("`{}`", v.to_json()),
        };
        s.push_str(&format!(
            "| {} | {} | {value} | {} |\n",
            text_of(t.get("rep")),
            text_of(t.get("def")),
            text_of(t.get("explain")),
        ));
    }
    s.push_str("\nThe records rebuilt from these triples:\n\n```text\n");
    for r in j
        .get("records")
        .and_then(Json::as_array)
        .ok_or("no records")?
    {
        s.push_str(&r.to_json());
        s.push('\n');
    }
    s.push_str("```\n");
    s.push_str(&conditions("nested.parquet", &bytes, None));
    Ok(s)
}

fn nested_runs_discounts(root: &Path) -> Result<String, String> {
    let (bytes, j) = nested_levels_json(root, "items.list.element.discounts.list.element")?;
    let page = j
        .get("pages")
        .and_then(Json::as_array)
        .and_then(|p| p.first())
        .ok_or("no pages")?;
    let mut s = String::from(HEADER);
    s.push_str("| Levels | Run | Header byte | Body bytes | Values |\n|---|---|---|---|---|\n");
    for (name, key) in [
        ("repetition", "repetition_levels"),
        ("definition", "definition_levels"),
    ] {
        let stream = page.get(key).ok_or("no levels")?;
        for run in stream
            .get("runs")
            .and_then(Json::as_array)
            .ok_or("no runs")?
        {
            let span_bytes = |k: &str| -> String {
                let sp = run
                    .get(k)
                    .and_then(Json::as_array)
                    .cloned()
                    .unwrap_or_default();
                let (a, b) = (
                    sp.first().and_then(Json::as_u64).unwrap_or(0) as usize,
                    sp.get(1).and_then(Json::as_u64).unwrap_or(0) as usize,
                );
                parquet_lab::encoding::hex(&bytes[a..b])
            };
            let values: Vec<String> = run
                .get("values")
                .and_then(Json::as_array)
                .map(|v| v.iter().map(|x| x.to_json()).collect())
                .unwrap_or_default();
            s.push_str(&format!(
                "| {name} | {} | `{}` | `{}` | {} |\n",
                text_of(run.get("kind")),
                span_bytes("header"),
                span_bytes("body"),
                values.join(", ")
            ));
        }
    }
    s.push_str(&conditions("nested.parquet", &bytes, None));
    Ok(s)
}

fn encodings_json(root: &Path, file: &str, path: &str) -> Result<(Vec<u8>, Json), String> {
    let bytes = fixture(root, file)?;
    let first = parquet_lab::report::encodings(&bytes, 0);
    let column = first
        .get("columns")
        .and_then(Json::as_array)
        .and_then(|cs| cs.iter().find(|c| text_of(c.get("path")) == path))
        .and_then(|c| c.get("column"))
        .and_then(Json::as_u64)
        .ok_or(format!("{file} has no column {path}"))?;
    let j = parquet_lab::report::encodings(&bytes, column as usize);
    if j.get("ok") != Some(&Json::Bool(true)) {
        return Err(format!("{file} {path}: {}", j.to_json()));
    }
    Ok((bytes, j))
}

fn encodings_sizes(root: &Path) -> Result<String, String> {
    let mut s = String::from(HEADER);
    s.push_str(
        "| File | Column | Encoding | Values | Stored | As PLAIN | Stored as a share of PLAIN |\n\
         |---|---|---|--:|--:|--:|--:|\n",
    );
    let mut sizes = Vec::new();
    for file in ["dictionary.parquet", "encodings.parquet"] {
        let bytes = fixture(root, file)?;
        sizes.push(format!("`{file}` is {} bytes", bytes.len()));
        let first = parquet_lab::report::encodings(&bytes, 0);
        for c in first
            .get("columns")
            .and_then(Json::as_array)
            .ok_or("no columns")?
        {
            let (_, j) = encodings_json(root, file, &text_of(c.get("path")))?;
            let sz = j.get("sizes").ok_or("no sizes")?;
            let (enc, plain) = (
                sz.get("encoded").and_then(Json::as_u64).unwrap_or(0),
                sz.get("plain").and_then(Json::as_u64).unwrap_or(0),
            );
            let encoding: Vec<String> = j
                .get("pages")
                .and_then(Json::as_array)
                .map(|ps| ps.iter().map(|p| text_of(p.get("encoding"))).collect())
                .unwrap_or_default();
            s.push_str(&format!(
                "| `{file}` | `{}` | {} | {} | {enc} bytes | {plain} bytes | {}% |\n",
                text_of(j.get("path")),
                encoding.join(", "),
                text_of(sz.get("count")),
                if plain == 0 {
                    0
                } else {
                    (enc * 100 + plain / 2) / plain
                },
            ));
        }
    }
    s.push_str(&format!(
        "\n*Computed by the reader from the fixtures: {}. Stored is the encoded values, plus the dictionary page's body where there is one; levels and page headers are in neither column.*\n",
        sizes.join(", ")
    ));
    Ok(s)
}

fn dictionary_country(root: &Path) -> Result<String, String> {
    let (bytes, j) = encodings_json(root, "dictionary.parquet", "country")?;
    let mut s = String::from(HEADER);
    s.push_str("The dictionary page:\n\n| Index | Value | Bytes |\n|--:|---|---|\n");
    let dict = j.get("dictionary").ok_or("no dictionary")?;
    for e in dict
        .get("entries")
        .and_then(Json::as_array)
        .ok_or("no entries")?
    {
        let sp = e.get("span").and_then(Json::as_array).ok_or("no span")?;
        let (a, b) = (
            sp[0].as_u64().unwrap_or(0) as usize,
            sp[1].as_u64().unwrap_or(0) as usize,
        );
        s.push_str(&format!(
            "| {} | `{}` | `{}` |\n",
            text_of(e.get("index")),
            text_of(e.get("value")),
            parquet_lab::encoding::hex(&bytes[a..b])
        ));
    }
    s.push_str(
        "\nThe data page's values:\n\n| Step | Bytes | What the decoder read |\n|---|---|---|\n",
    );
    for p in j.get("pages").and_then(Json::as_array).ok_or("no pages")? {
        for st in p.get("steps").and_then(Json::as_array).ok_or("no steps")? {
            let sp = st.get("span").and_then(Json::as_array).ok_or("no span")?;
            let (a, b) = (
                sp[0].as_u64().unwrap_or(0) as usize,
                sp[1].as_u64().unwrap_or(0) as usize,
            );
            s.push_str(&format!(
                "| {} | `{}` | {} |\n",
                text_of(st.get("label")),
                parquet_lab::encoding::hex(&bytes[a..b]),
                text_of(st.get("detail"))
            ));
        }
    }
    let values: Vec<String> = j
        .get("values")
        .and_then(Json::as_array)
        .map(|v| v.iter().map(|x| text_of(x.get("value"))).collect())
        .unwrap_or_default();
    s.push_str(&format!("\nDecoded, in order: {}.\n", values.join(", ")));
    s.push_str(&conditions("dictionary.parquet", &bytes, None));
    Ok(s)
}

fn steps_table(bytes: &[u8], j: &Json, limit: usize) -> Result<String, String> {
    let mut s = String::from("| Step | Bytes | What the decoder read |\n|---|---|---|\n");
    for p in j.get("pages").and_then(Json::as_array).ok_or("no pages")? {
        for st in p
            .get("steps")
            .and_then(Json::as_array)
            .ok_or("no steps")?
            .iter()
            .take(limit)
        {
            let sp = st.get("span").and_then(Json::as_array).ok_or("no span")?;
            let (a, b) = (
                sp[0].as_u64().unwrap_or(0) as usize,
                sp[1].as_u64().unwrap_or(0) as usize,
            );
            let hex = if b - a > 12 {
                format!(
                    "{} … ({} bytes)",
                    parquet_lab::encoding::hex(&bytes[a..a + 12]),
                    b - a
                )
            } else if a == b {
                "(none)".to_string()
            } else {
                parquet_lab::encoding::hex(&bytes[a..b])
            };
            s.push_str(&format!(
                "| {} | `{hex}` | {} |\n",
                text_of(st.get("label")),
                text_of(st.get("detail"))
            ));
        }
    }
    Ok(s)
}

fn delta_ordered_at(root: &Path) -> Result<String, String> {
    let (bytes, j) = encodings_json(root, "encodings.parquet", "ordered_at")?;
    let mut s = String::from(HEADER);
    s.push_str(&steps_table(&bytes, &j, 8)?);
    let values: Vec<String> = j
        .get("values")
        .and_then(Json::as_array)
        .map(|v| v.iter().take(5).map(|x| text_of(x.get("value"))).collect())
        .unwrap_or_default();
    s.push_str(&format!("\nThe first values: {}, …\n", values.join(", ")));
    s.push_str(&conditions("encodings.parquet", &bytes, None));
    Ok(s)
}

fn delta_urls(root: &Path) -> Result<String, String> {
    let bytes = fixture(root, "encodings.parquet")?;
    let md = open_bytes(&bytes)?;
    let rootn = parquet_lab::schema::build(&md.schema).map_err(|e| e.to_string())?;
    let leaves = parquet_lab::schema::leaves(&rootn);
    let leaf = leaves
        .iter()
        .find(|l| l.dotted_path() == "url")
        .ok_or("no url column")?;
    let data =
        parquet_lab::column::read_column(&bytes, &md.row_groups[0].columns[leaf.column], leaf)
            .map_err(|e| e.to_string())?;
    let page = data.pages.first().ok_or("no page")?;
    let body = &bytes[page.values.start as usize..page.values.end as usize];
    let deltas =
        parquet_lab::delta::binary_packed(body, page.values.start).map_err(|e| e.to_string())?;
    let (prefixes, end) = (deltas.values, deltas.end);
    let suffixes =
        parquet_lab::delta::length_byte_array(&body[(end - page.values.start) as usize..], end)
            .map_err(|e| e.to_string())?;
    let mut s = String::from(HEADER);
    s.push_str(
        "| # | Shared with the previous value | Stored suffix | Value |\n|--:|--:|---|---|\n",
    );
    for (i, (((p, _), suf), t)) in prefixes
        .iter()
        .zip(&suffixes.values)
        .zip(&data.triples)
        .take(12)
        .enumerate()
    {
        let show = |v: &parquet_lab::plain::PlainValue| text_of(Some(&v.to_json()));
        s.push_str(&format!(
            "| {i} | {p} | `{}` | `{}` |\n",
            show(&suf.value),
            t.value.as_ref().map(show).unwrap_or_default()
        ));
    }
    s.push_str(&conditions("encodings.parquet", &bytes, None));
    Ok(s)
}

fn split_weights(root: &Path) -> Result<String, String> {
    let (bytes, j) = encodings_json(root, "encodings.parquet", "weight_kg")?;
    let page = j
        .get("pages")
        .and_then(Json::as_array)
        .and_then(|p| p.first())
        .ok_or("no page")?;
    let mut s = String::from(HEADER);
    s.push_str("| Stream | Holds | First twelve bytes | Distinct bytes in the stream |\n|---|---|---|--:|\n");
    for st in page
        .get("steps")
        .and_then(Json::as_array)
        .ok_or("no steps")?
    {
        let sp = st.get("span").and_then(Json::as_array).ok_or("no span")?;
        let (a, b) = (
            sp[0].as_u64().unwrap_or(0) as usize,
            sp[1].as_u64().unwrap_or(0) as usize,
        );
        let mut distinct: Vec<u8> = bytes[a..b].to_vec();
        distinct.sort_unstable();
        distinct.dedup();
        s.push_str(&format!(
            "| {} | {} | `{}` | {} |\n",
            text_of(st.get("label")),
            text_of(st.get("detail")),
            parquet_lab::encoding::hex(&bytes[a..(a + 12).min(b)]),
            distinct.len()
        ));
    }
    s.push_str(&conditions("encodings.parquet", &bytes, None));
    Ok(s)
}
